<script type="text/javascript" src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/swiper-bundle.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/carousel.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/bootstrap-select.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/lazysize.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/count-down.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/wow.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/multiple-modal.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/main.js') }}"></script>
